name: Node.js CI and Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: npm install and test
      run: |
        npm install
        npm test

    - name: Coveralls
      uses: coverallsapp/github-action@v2


            
